/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdlib.h> // for NULL
#include <assert.h>
#include <string.h>
#include "gain_control.h"
/* Header for class com_qd_gtcom_wangzhengcheng_agc_AgcUtils */

#include "Platform.h"


#ifndef _Included_com_qd_gtcom_wangzhengcheng_agc_AgcUtils
#define _Included_com_qd_gtcom_wangzhengcheng_agc_AgcUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qd_gtcom_wangzhengcheng_agc_AgcUtils
 * Method:    create
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_qd_gtcom_wangzhengcheng_agc_AgcUtils_create
        (JNIEnv *env, jclass jclazz){

    void *agcInstance = NULL;
    WebRtcAgc_Create(&agcInstance);
    return ((int) agcInstance);

}

/*
 * Class:     com_qd_gtcom_wangzhengcheng_agc_AgcUtils
 * Method:    init
 * Signature: (IIIII)I
 */
JNIEXPORT jint JNICALL Java_com_qd_gtcom_wangzhengcheng_agc_AgcUtils_init
        (JNIEnv *env, jclass jclazz, jint agcInstance, jint minLevel, jint maxLevel, jint agcMode, jint fs){

    void *agcInst = (void *) agcInstance;
    if (agcInst == NULL)
        return -5;

    return WebRtcAgc_Init(agcInst,minLevel,maxLevel,kAgcModeFixedDigital,fs);
}

/*
 * Class:     com_qd_gtcom_wangzhengcheng_agc_AgcUtils
 * Method:    free
 * Signature: (I)V
 */
JNIEXPORT jint JNICALL Java_com_qd_gtcom_wangzhengcheng_agc_AgcUtils_free
(JNIEnv *env, jclass jclazz, jint agcInstance){
    void *agcInst = (void *) agcInstance;
    if (agcInst == NULL)
        return -2;
    return WebRtcAgc_Free(agcInst);

}

/*
 * Class:     com_qd_gtcom_wangzhengcheng_agc_AgcUtils
 * Method:    process
 * Signature: (I[SII[SIIII)I
 */
JNIEXPORT jint JNICALL Java_com_qd_gtcom_wangzhengcheng_agc_AgcUtils_process
        (JNIEnv *env, jclass jclazz, jint agcInstance, const jshortArray inNear, jint num_bands, jint samples, jshortArray out, jint inMicLevel, jint outMicLevel, jint echo, jint saturationWarning){

        int16_t *arrNear = NULL;
        int16_t *arrOut = NULL;
        int32_t *outMicLevel1 = NULL;
        uint8_t *test = NULL;
        const int16_t* inNear_H = NULL;
        int16_t* out_H = NULL;


        void *agcInst = (void *) agcInstance;
        if(agcInst == NULL)
        return -1;

        int ret = -1;


        arrNear = (*env)->GetShortArrayElements(env,inNear, NULL);
        arrOut = (*env)->GetShortArrayElements(env,out, NULL);

        ret = WebRtcAgc_Process(agcInst,arrNear,inNear_H,samples,arrOut,out_H,inMicLevel,&outMicLevel1,echo,&test);

        //release and send the changes back to java side.
        (*env)->ReleaseShortArrayElements(env,inNear, arrNear, 0);
        (*env)->ReleaseShortArrayElements(env,out, arrOut, 0);

         return ret;
}

/*
 * Class:     com_qd_gtcom_wangzhengcheng_agc_AgcUtils
 * Method:    setConfig
 * Signature: (ILcom/qd/gtcom/wangzhengcheng/agc/AgcUtils/WebRtcAgcConfig;)I
 */
JNIEXPORT jint JNICALL Java_com_qd_gtcom_wangzhengcheng_agc_AgcUtils_setConfig
        (JNIEnv *env, jclass jclazz, jint agcInstance, jobject agcConfig){

        void * agcInst = (void *) agcInstance;
        if (agcInst == NULL)
        return -1;

        jclass JavaWebRtcAgcConfig = (*env)->GetObjectClass(env,agcConfig);
        assert(JavaWebRtcAgcConfig != NULL);
        jfieldID targetLevelDbfsID = (*env)->GetFieldID(env,JavaWebRtcAgcConfig, "targetLevelDbfs",
                                       "I");
        jfieldID compressionGaindBID = (*env)->GetFieldID(env,JavaWebRtcAgcConfig, "compressionGaindB",
                                      "I");
        jfieldID limiterEnableID = (*env)->GetFieldID(env,JavaWebRtcAgcConfig, "limiterEnable",
                                      "I");
        if (targetLevelDbfsID == NULL || compressionGaindBID == NULL || limiterEnableID == NULL)
        return -1;

        int targetLevelDbfsMode = (*env)->GetIntField(env,agcConfig, targetLevelDbfsID);
        int compressionGaindBMode = (*env)->GetIntField(env,agcConfig, compressionGaindBID);
        int limiterEnableMode = (*env)->GetIntField(env,agcConfig, limiterEnableID);

        WebRtcAgc_config_t config;
        config.targetLevelDbfs = targetLevelDbfsMode;
        config.compressionGaindB = compressionGaindBMode;
        config.limiterEnable = limiterEnableMode;

        return WebRtcAgc_set_config(agcInst,config);
}

/*
 * Class:     com_qd_gtcom_wangzhengcheng_agc_AgcUtils
 * Method:    addFarend
 * Signature: (I[SI)I
 */
JNIEXPORT jint JNICALL Java_com_qd_gtcom_wangzhengcheng_agc_AgcUtils_addFarend
        (JNIEnv *env, jclass jclazz, jint agcInstance, jshortArray inFar, jint samples){
    return 0;
}

/*
 * Class:     com_qd_gtcom_wangzhengcheng_agc_AgcUtils
 * Method:    addMic
 * Signature: (I[SII)I
 */
JNIEXPORT jint JNICALL Java_com_qd_gtcom_wangzhengcheng_agc_AgcUtils_addMic
        (JNIEnv *env, jclass jclazz, jint agcInstance, jshortArray inMic, jint num_bands, jint samples){
    return 0;
}

/*
 * Class:     com_qd_gtcom_wangzhengcheng_agc_AgcUtils
 * Method:    getConfig
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_qd_gtcom_wangzhengcheng_agc_AgcUtils_getConfig
        (JNIEnv *, jclass);

/*
 * Class:     com_qd_gtcom_wangzhengcheng_agc_AgcUtils
 * Method:    virtualMic
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_qd_gtcom_wangzhengcheng_agc_AgcUtils_virtualMic
        (JNIEnv *, jclass);

/*
 * Class:     com_qd_gtcom_wangzhengcheng_agc_AgcUtils
 * Method:    getAddFarendError
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_qd_gtcom_wangzhengcheng_agc_AgcUtils_getAddFarendError
        (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
